// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj68tP59TDO3CANekZ9ZHhv-_7O1x3jpk',
    appId: '1:702107243931:web:3dbc64d55dd0dd0cb67d3e',
    messagingSenderId: '702107243931',
    projectId: 'finance-management-app-ec414',
    authDomain: 'finance-management-app-ec414.firebaseapp.com',
    storageBucket: 'finance-management-app-ec414.appspot.com',
    measurementId: 'G-C6WXP8TXZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbxlxvgUSGY5VoD5bqa_rDv1lK78Jst38',
    appId: '1:702107243931:android:702317919eeb30f8b67d3e',
    messagingSenderId: '702107243931',
    projectId: 'finance-management-app-ec414',
    storageBucket: 'finance-management-app-ec414.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACSLWS9iaA7msqxUgw9ukJUGDvdMDAuGc',
    appId: '1:702107243931:ios:c61ccc6de8290b59b67d3e',
    messagingSenderId: '702107243931',
    projectId: 'finance-management-app-ec414',
    storageBucket: 'finance-management-app-ec414.appspot.com',
    iosClientId: '702107243931-l10roeusnjcm72lmrt5d8i5k8h60cvh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACSLWS9iaA7msqxUgw9ukJUGDvdMDAuGc',
    appId: '1:702107243931:ios:c61ccc6de8290b59b67d3e',
    messagingSenderId: '702107243931',
    projectId: 'finance-management-app-ec414',
    storageBucket: 'finance-management-app-ec414.appspot.com',
    iosClientId: '702107243931-l10roeusnjcm72lmrt5d8i5k8h60cvh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeManagementApp',
  );
}
